Debugged ccdb.m4 macro and generated configure script with it. Still not tested.
git-svn-id: https://phys12svn.jlab.org/repos/JANA@1241 c5ed4466-e916-0410-8347-b3263e9c103d

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -650,6 +650,10 @@ OS
 CURL_LIBS
 CURL_CFLAGS
 CURL_PREFIX
+CCDB_LIBS
+CCDB_LDFLAGS
+CCDB_CPPFLAGS
+CCDB_HOME
 CMSG_LIBS
 CMSG_LDFLAGS
 CMSG_CPPFLAGS
@@ -742,6 +746,7 @@ with_xerces_inc
 with_xerces_lib
 with_rootsys
 with_cmsg
+with_ccdb
 with_curl
 '
       ac_precious_vars='build_alias
@@ -1384,6 +1389,7 @@ Optional Packages:
   --with-xerces-lib=[ARG] link options for Xerces C++ Parser libraries
   --with-rootsys          top of the ROOT installation directory
   --with-cmsg[=DIR]       include cMsg support (with cMsg install dir)
+  --with-ccdb[=DIR]       include CCDB support (with CCDB install dir)
   --with-curl             include cURL library support
 
 Some influential environment variables:
@@ -5375,6 +5381,362 @@ $as_echo_n "checking for cMsg... " >&6; }
 		{ $as_echo "$as_me:$LINENO: result: no" >&5
 $as_echo "no" >&6; }
 	fi # test ! "$user_cmsg" = "no"
+
+
+
+	HAVE_CCDB="0"
+
+	# The behavior we want here is that if the user doesn't specify whether to
+	# include CCDB or not, then we look to see if the CCDB_HOME environment
+	# variable is set. If it is, then we will automatically try to include it.
+	# If it is not set, and the --with[out]-ccdb command line switch is not
+	# specified, then we disable CCDB support.
+
+# Check whether --with-ccdb was given.
+if test "${with_ccdb+set}" = set; then
+  withval=$with_ccdb; user_ccdb=$withval
+else
+  user_ccdb="notspecified"
+fi
+
+
+	if test "$user_ccdb" = "notspecified"; then
+		if test ! x"$CCDB_HOME" = x ; then
+			user_ccdb="yes"
+		else
+			user_ccdb="no"
+		fi
+	fi
+
+	if test ! "$user_ccdb" = "no"; then
+		HAVE_CCDB="1"
+
+		if test ! x"$user_ccdb" = xyes; then
+			ccdb_dir="$user_ccdb"
+		elif test ! x"$CCDB_HOME" = x ; then
+			ccdb_dir="$CCDB_HOME"
+		else
+			ccdb_dir="/usr/local"
+		fi
+
+		{ $as_echo "$as_me:$LINENO: checking Looking for CCDB in $ccdb_dir" >&5
+$as_echo_n "checking Looking for CCDB in $ccdb_dir... " >&6; }
+		if test ! -d $ccdb_dir; then
+			{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+			HAVE_CCDB="0"
+		else
+			{ $as_echo "$as_me:$LINENO: result: yes" >&5
+$as_echo "yes" >&6; }
+
+			CCDB_CPPFLAGS=-I$ccdb_dir/include
+			CCDB_LDFLAGS=-L$ccdb_dir/lib
+			CCDB_LIBS='-lccdb'
+
+			save_CPPFLAGS=$CPPFLAGS
+			save_LDFLAGS=$LDFLAGS
+			save_LIBS=$LIBS
+
+			CPPFLAGS=$CCDB_CPPFLAGS
+			LDFLAGS=$CCDB_LDFLAGS
+			LIBS=$CCDB_LIBS
+
+			ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+			if test "${ac_cv_header_CCDB_CalibrationGenerator_h+set}" = set; then
+  { $as_echo "$as_me:$LINENO: checking for CCDB/CalibrationGenerator.h" >&5
+$as_echo_n "checking for CCDB/CalibrationGenerator.h... " >&6; }
+if test "${ac_cv_header_CCDB_CalibrationGenerator_h+set}" = set; then
+  $as_echo_n "(cached) " >&6
+fi
+{ $as_echo "$as_me:$LINENO: result: $ac_cv_header_CCDB_CalibrationGenerator_h" >&5
+$as_echo "$ac_cv_header_CCDB_CalibrationGenerator_h" >&6; }
+else
+  # Is the header compilable?
+{ $as_echo "$as_me:$LINENO: checking CCDB/CalibrationGenerator.h usability" >&5
+$as_echo_n "checking CCDB/CalibrationGenerator.h usability... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <CCDB/CalibrationGenerator.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ $as_echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+$as_echo "$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ $as_echo "$as_me:$LINENO: checking CCDB/CalibrationGenerator.h presence" >&5
+$as_echo_n "checking CCDB/CalibrationGenerator.h presence... " >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <CCDB/CalibrationGenerator.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_cxx_preproc_warn_flag$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ $as_echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+$as_echo "$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_cxx_preproc_warn_flag in
+  yes:no: )
+    { $as_echo "$as_me:$LINENO: WARNING: CCDB/CalibrationGenerator.h: accepted by the compiler, rejected by the preprocessor!" >&5
+$as_echo "$as_me: WARNING: CCDB/CalibrationGenerator.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: CCDB/CalibrationGenerator.h: proceeding with the compiler's result" >&5
+$as_echo "$as_me: WARNING: CCDB/CalibrationGenerator.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { $as_echo "$as_me:$LINENO: WARNING: CCDB/CalibrationGenerator.h: present but cannot be compiled" >&5
+$as_echo "$as_me: WARNING: CCDB/CalibrationGenerator.h: present but cannot be compiled" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: CCDB/CalibrationGenerator.h:     check for missing prerequisite headers?" >&5
+$as_echo "$as_me: WARNING: CCDB/CalibrationGenerator.h:     check for missing prerequisite headers?" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: CCDB/CalibrationGenerator.h: see the Autoconf documentation" >&5
+$as_echo "$as_me: WARNING: CCDB/CalibrationGenerator.h: see the Autoconf documentation" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: CCDB/CalibrationGenerator.h:     section \"Present But Cannot Be Compiled\"" >&5
+$as_echo "$as_me: WARNING: CCDB/CalibrationGenerator.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: CCDB/CalibrationGenerator.h: proceeding with the preprocessor's result" >&5
+$as_echo "$as_me: WARNING: CCDB/CalibrationGenerator.h: proceeding with the preprocessor's result" >&2;}
+    { $as_echo "$as_me:$LINENO: WARNING: CCDB/CalibrationGenerator.h: in the future, the compiler will take precedence" >&5
+$as_echo "$as_me: WARNING: CCDB/CalibrationGenerator.h: in the future, the compiler will take precedence" >&2;}
+
+    ;;
+esac
+{ $as_echo "$as_me:$LINENO: checking for CCDB/CalibrationGenerator.h" >&5
+$as_echo_n "checking for CCDB/CalibrationGenerator.h... " >&6; }
+if test "${ac_cv_header_CCDB_CalibrationGenerator_h+set}" = set; then
+  $as_echo_n "(cached) " >&6
+else
+  ac_cv_header_CCDB_CalibrationGenerator_h=$ac_header_preproc
+fi
+{ $as_echo "$as_me:$LINENO: result: $ac_cv_header_CCDB_CalibrationGenerator_h" >&5
+$as_echo "$ac_cv_header_CCDB_CalibrationGenerator_h" >&6; }
+
+fi
+if test "x$ac_cv_header_CCDB_CalibrationGenerator_h" = x""yes; then
+  h=1
+else
+  h=0
+fi
+
+
+
+			{ $as_echo "$as_me:$LINENO: checking if ccdb needs libmysql to link" >&5
+$as_echo_n "checking if ccdb needs libmysql to link... " >&6; }
+			ccdb_link_ok=no
+			cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <CCDB/CalibrationGenerator.h>
+int
+main ()
+{
+new ccdb::CalibrationGenerator();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 $as_test_x conftest$ac_exeext
+       }; then
+  ccdb_link_ok=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -rf conftest.dSYM
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+
+			if test "$ccdb_link_ok" = "no"; then
+				ccdb_link_ok=failed
+				CCDB_LIBS+=' -lmysql'
+				LIBS=$CCDB_LIBS
+				cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <CCDB/CalibrationGenerator.h>
+int
+main ()
+{
+new ccdb::CalibrationGenerator();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval ac_try_echo="\"\$as_me:$LINENO: $ac_try_echo\""
+$as_echo "$ac_try_echo") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  $as_echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_cxx_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext && {
+	 test "$cross_compiling" = yes ||
+	 $as_test_x conftest$ac_exeext
+       }; then
+  ccdb_link_ok=yes
+else
+  $as_echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+
+fi
+
+rm -rf conftest.dSYM
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+			else
+				# we get here if the first link attempt succeeded and ccdb_link_ok=yes
+				# We set it to "no" to indicate -lmysql was not needed (confusing isn't it?)
+				ccdb_link_ok=no
+			fi
+
+			{ $as_echo "$as_me:$LINENO: result: $ccdb_link_ok" >&5
+$as_echo "$ccdb_link_ok" >&6; };
+
+			if test "$ccdb_link_ok" = "failed"; then
+				{ { $as_echo "$as_me:$LINENO: error: \"Test link of CCDB failed (using path=$ccdb_dir). Set your CCDB_HOME environment variable or use the --with-ccdb=PATH_TO_CCDB argument when running configure\"" >&5
+$as_echo "$as_me: error: \"Test link of CCDB failed (using path=$ccdb_dir). Set your CCDB_HOME environment variable or use the --with-ccdb=PATH_TO_CCDB argument when running configure\"" >&2;}
+   { (exit 1); exit 1; }; }
+			fi
+
+			ac_ext=cpp
+ac_cpp='$CXXCPP $CPPFLAGS'
+ac_compile='$CXX -c $CXXFLAGS $CPPFLAGS conftest.$ac_ext >&5'
+ac_link='$CXX -o conftest$ac_exeext $CXXFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
+ac_compiler_gnu=$ac_cv_cxx_compiler_gnu
+
+
+			CPPFLAGS="$save_CPPFLAGS $CCDB_CPPFLAGS"
+			LDFLAGS="$save_LDFLAGS $CCDB_LDFLAGS"
+			LIBS="$save_LIBS $CCDB_LIBS"
+			CCDB_DIR=$ccdb_dir
+		fi
+
+		if test "$HAVE_CCDB" = "0"; then
+			{ $as_echo "$as_me:$LINENO: \"Can't find CCDB (using path=$ccdb_dir). \"" >&5
+$as_echo "$as_me: \"Can't find CCDB (using path=$ccdb_dir). \"" >&6;}
+			{ $as_echo "$as_me:$LINENO: \"Set your CCDB_HOME environment variable or use the --with-ccdb=PATH_TO_CCDB\"" >&5
+$as_echo "$as_me: \"Set your CCDB_HOME environment variable or use the --with-ccdb=PATH_TO_CCDB\"" >&6;}
+			{ $as_echo "$as_me:$LINENO: \"argument when running configure. Otherwise disable CCDB support by\"" >&5
+$as_echo "$as_me: \"argument when running configure. Otherwise disable CCDB support by\"" >&6;}
+			{ $as_echo "$as_me:$LINENO: \"re-running configure with --without-ccdb.\"" >&5
+$as_echo "$as_me: \"re-running configure with --without-ccdb.\"" >&6;}
+		else
+			CCDB_HOME="$ccdb_dir"
+			{ $as_echo "$as_me:$LINENO: Configuring CCDB" >&5
+$as_echo "$as_me: Configuring CCDB" >&6;}
+
+
+
+
+		fi
+
+	else
+		{ $as_echo "$as_me:$LINENO: checking for CCDB" >&5
+$as_echo_n "checking for CCDB... " >&6; }
+		{ $as_echo "$as_me:$LINENO: result: no" >&5
+$as_echo "no" >&6; }
+	fi # test ! "$user_ccdb" = "no"
 
 
 
